{
  "scan_info": {
    "target": "/home/s3zer0/system-security/test_target/pyyaml-vuln.tar",
    "scan_date": "2025-10-11T04:02:07.816905355Z",
    "os_info": {
      "Family": "debian",
      "Name": "13.1"
    }
  },
  "vulnerability_summary": {
    "total_vulnerabilities": 13,
    "by_severity": {
      "HIGH": 6,
      "CRITICAL": 1,
      "MEDIUM": 5,
      "LOW": 1
    },
    "by_package_type": {
      "python-pkg": 13
    }
  },
  "vulnerabilities": [
    {
      "id": "CVE-2023-30861",
      "package_name": "Flask",
      "installed_version": "2.0.2",
      "severity": "HIGH",
      "title": "flask: Possible disclosure of permanent session cookie due to missing Vary: Cookie header",
      "description": "Flask is a lightweight WSGI web application framework. When all of the following conditions are met, a response containing data intended for one client may be cached and subsequently sent by the proxy to other clients. If the proxy also caches `Set-Cookie` headers, it may send one client's `session` cookie to other clients. The severity depends on the application's use of the session and the proxy's behavior regarding cookies. The risk depends on all these conditions being met.\n\n1. The application must be hosted behind a caching proxy that does not strip cookies or ignore responses with cookies.\n2. The application sets `session.permanent = True`\n3. The application does not access or modify the session at any point during a request.\n4. `SESSION_REFRESH_EACH_REQUEST` enabled (the default).\n5. The application does not set a `Cache-Control` header to indicate that a page is private or should not be cached.\n\nThis happens because vulnerable versions of Flask only set the `Vary: Cookie` header when the session is accessed or modified, not when it is refreshed (re-sent to update the expiration) without being accessed or modified. This issue has been fixed in versions 2.3.2 and 2.2.5.",
      "fixed_version": "2.3.2, 2.2.5",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
          "V3Score": 7.5
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
          "V3Score": 7.5
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
          "V3Score": 7.5
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2023-30861",
        "https://github.com/pallets/flask",
        "https://github.com/pallets/flask/commit/70f906c51ce49c485f1d355703e9cc3386b1cc2b",
        "https://github.com/pallets/flask/commit/8646edca6f47e2cd57464081b3911218d4734f8d (2.2.5)",
        "https://github.com/pallets/flask/commit/8705dd39c4fa563ea0fe0bf84c85da8fcc98b88d (2.3.2)",
        "https://github.com/pallets/flask/commit/afd63b16170b7c047f5758eb910c416511e9c965",
        "https://github.com/pallets/flask/releases/tag/2.2.5",
        "https://github.com/pallets/flask/releases/tag/2.3.2",
        "https://github.com/pallets/flask/security/advisories/GHSA-m2qf-hxjv-5gpq",
        "https://github.com/pypa/advisory-database/tree/main/vulns/flask/PYSEC-2023-62.yaml",
        "https://linux.oracle.com/cve/CVE-2023-30861.html",
        "https://linux.oracle.com/errata/ELSA-2023-12710.html",
        "https://lists.debian.org/debian-lts-announce/2023/08/msg00024.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-30861",
        "https://security.netapp.com/advisory/ntap-20230818-0006",
        "https://security.netapp.com/advisory/ntap-20230818-0006/",
        "https://ubuntu.com/security/notices/USN-6111-1",
        "https://www.cve.org/CVERecord?id=CVE-2023-30861",
        "https://www.debian.org/security/2023/dsa-5442"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2023-30861",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2020-14343",
      "package_name": "PyYAML",
      "installed_version": "5.3.1",
      "severity": "CRITICAL",
      "title": "PyYAML: incomplete fix for CVE-2020-1747",
      "description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
      "fixed_version": "5.4",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "V3Score": 9.8
        },
        "nvd": {
          "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "V2Score": 10,
          "V3Score": 9.8
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "V3Score": 9.8
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2020-14343",
        "https://bugzilla.redhat.com/show_bug.cgi?id=1860466",
        "https://errata.almalinux.org/8/ALSA-2021-2583.html",
        "https://github.com/SeldonIO/seldon-core/issues/2252",
        "https://github.com/advisories/GHSA-8q59-q68h-6hv4",
        "https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml",
        "https://github.com/yaml/pyyaml",
        "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc",
        "https://github.com/yaml/pyyaml/issues/420",
        "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966",
        "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation",
        "https://linux.oracle.com/cve/CVE-2020-14343.html",
        "https://linux.oracle.com/errata/ELSA-2021-2583.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2020-14343",
        "https://pypi.org/project/PyYAML",
        "https://ubuntu.com/security/notices/USN-4940-1",
        "https://www.cve.org/CVERecord?id=CVE-2020-14343",
        "https://www.oracle.com/security-alerts/cpuapr2022.html",
        "https://www.oracle.com/security-alerts/cpujul2022.html"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2020-14343",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2023-25577",
      "package_name": "Werkzeug",
      "installed_version": "2.0.2",
      "severity": "HIGH",
      "title": "python-werkzeug: high resource usage when parsing multipart form data with many fields",
      "description": "Werkzeug is a comprehensive WSGI web application library. Prior to version 2.2.3, Werkzeug's multipart form data parser will parse an unlimited number of parts, including file parts. Parts can be a small amount of bytes, but each requires CPU time to parse and may use more memory as Python data. If a request can be made to an endpoint that accesses `request.data`, `request.form`, `request.files`, or `request.get_data(parse_form_data=False)`, it can cause unexpectedly high resource usage. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. Unlimited file parts can use up memory and file handles. If many concurrent requests are sent continuously, this can exhaust or kill all available workers. Version 2.2.3 contains a patch for this issue.",
      "fixed_version": "2.2.3",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2023-25577",
        "https://github.com/pallets/werkzeug",
        "https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1",
        "https://github.com/pallets/werkzeug/releases/tag/2.2.3",
        "https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323",
        "https://github.com/pypa/advisory-database/tree/main/vulns/werkzeug/PYSEC-2023-58.yaml",
        "https://linux.oracle.com/cve/CVE-2023-25577.html",
        "https://linux.oracle.com/errata/ELSA-2023-12709.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-25577",
        "https://security.netapp.com/advisory/ntap-20230818-0003",
        "https://security.netapp.com/advisory/ntap-20230818-0003/",
        "https://ubuntu.com/security/notices/USN-5948-1",
        "https://ubuntu.com/security/notices/USN-5948-2",
        "https://www.cve.org/CVERecord?id=CVE-2023-25577",
        "https://www.debian.org/security/2023/dsa-5470"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2023-25577",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2024-34069",
      "package_name": "Werkzeug",
      "installed_version": "2.0.2",
      "severity": "HIGH",
      "title": "python-werkzeug: user may execute code on a developer's machine",
      "description": "Werkzeug is a comprehensive WSGI web application library. The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger. This vulnerability is fixed in 3.0.3.",
      "fixed_version": "3.0.3",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "V3Score": 7.5
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "V3Score": 7.5
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2024-34069",
        "https://github.com/pallets/werkzeug",
        "https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692",
        "https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985",
        "https://lists.debian.org/debian-lts-announce/2025/02/msg00026.html",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/",
        "https://nvd.nist.gov/vuln/detail/CVE-2024-34069",
        "https://security.netapp.com/advisory/ntap-20240614-0004",
        "https://security.netapp.com/advisory/ntap-20240614-0004/",
        "https://ubuntu.com/security/notices/USN-6799-1",
        "https://www.cve.org/CVERecord?id=CVE-2024-34069"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2024-34069",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2023-46136",
      "package_name": "Werkzeug",
      "installed_version": "2.0.2",
      "severity": "MEDIUM",
      "title": "python-werkzeug: high resource consumption leading to denial of service",
      "description": "Werkzeug is a comprehensive WSGI web application library. If an upload of a file that starts with CR or LF and then is followed by megabytes of data without these characters: all of these bytes are appended chunk by chunk into internal bytearray and lookup for boundary is performed on growing buffer. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. This vulnerability has been patched in version 3.0.1.",
      "fixed_version": "3.0.1, 2.3.8",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 5.7
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2023-46136",
        "https://github.com/pallets/werkzeug",
        "https://github.com/pallets/werkzeug/commit/b1916c0c083e0be1c9d887ee2f3d696922bfc5c1",
        "https://github.com/pallets/werkzeug/commit/f2300208d5e2a5076cbbb4c2aad71096fd040ef9",
        "https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2",
        "https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw",
        "https://github.com/pypa/advisory-database/tree/main/vulns/werkzeug/PYSEC-2023-221.yaml",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-46136",
        "https://security.netapp.com/advisory/ntap-20231124-0008",
        "https://security.netapp.com/advisory/ntap-20231124-0008/",
        "https://www.cve.org/CVERecord?id=CVE-2023-46136"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2023-46136",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2024-49766",
      "package_name": "Werkzeug",
      "installed_version": "2.0.2",
      "severity": "MEDIUM",
      "title": "werkzeug: python-werkzeug: Werkzeug safe_join not safe on Windows",
      "description": "Werkzeug is a Web Server Gateway Interface web application library. On Python < 3.11 on Windows, os.path.isabs() does not catch UNC paths like //server/share. Werkzeug's safe_join() relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable. Werkzeug version 3.0.6 contains a patch.",
      "fixed_version": "3.0.6",
      "cvss": {
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
          "V3Score": 3.7
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2024-49766",
        "https://github.com/pallets/werkzeug",
        "https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092",
        "https://github.com/pallets/werkzeug/releases/tag/3.0.6",
        "https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j",
        "https://nvd.nist.gov/vuln/detail/CVE-2024-49766",
        "https://security.netapp.com/advisory/ntap-20250131-0005",
        "https://security.netapp.com/advisory/ntap-20250131-0005/",
        "https://www.cve.org/CVERecord?id=CVE-2024-49766"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2024-49766",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2024-49767",
      "package_name": "Werkzeug",
      "installed_version": "2.0.2",
      "severity": "MEDIUM",
      "title": "werkzeug: python-werkzeug: Werkzeug possible resource exhaustion when parsing file data in forms",
      "description": "Werkzeug is a Web Server Gateway Interface web application library. Applications using `werkzeug.formparser.MultiPartParser` corresponding to a version of Werkzeug prior to 3.0.6 to parse `multipart/form-data` requests (e.g. all flask applications) are vulnerable to a relatively simple but effective resource exhaustion (denial of service) attack. A specifically crafted form submission request can cause the parser to allocate and block 3 to 8 times the upload size in main memory. There is no upper limit; a single upload at 1 Gbit/s can exhaust 32 GB of RAM in less than 60 seconds. Werkzeug version 3.0.6 fixes this issue.",
      "fixed_version": "3.0.6",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
          "V3Score": 5.3
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2024-49767",
        "https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee",
        "https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f",
        "https://github.com/pallets/werkzeug",
        "https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b",
        "https://github.com/pallets/werkzeug/releases/tag/3.0.6",
        "https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2",
        "https://nvd.nist.gov/vuln/detail/CVE-2024-49767",
        "https://security.netapp.com/advisory/ntap-20250103-0007",
        "https://security.netapp.com/advisory/ntap-20250103-0007/",
        "https://ubuntu.com/security/notices/USN-7093-1",
        "https://www.cve.org/CVERecord?id=CVE-2024-49767"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2024-49767",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2023-23934",
      "package_name": "Werkzeug",
      "installed_version": "2.0.2",
      "severity": "LOW",
      "title": "python-werkzeug: cookie prefixed with = can shadow unprefixed cookie",
      "description": "Werkzeug is a comprehensive WSGI web application library. Browsers may allow \"nameless\" cookies that look like `=value` instead of `key=value`. A vulnerable browser may allow a compromised application on an adjacent subdomain to exploit this to set a cookie like `=__Host-test=bad` for another subdomain. Werkzeug prior to 2.2.3 will parse the cookie `=__Host-test=bad` as __Host-test=bad`. If a Werkzeug application is running next to a vulnerable or malicious subdomain which sets such a cookie using a vulnerable browser, the Werkzeug application will see the bad cookie value but the valid cookie key. The issue is fixed in Werkzeug 2.2.3.",
      "fixed_version": "2.2.3",
      "cvss": {
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
          "V3Score": 2.6
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
          "V3Score": 3.5
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
          "V3Score": 2.6
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2023-23934",
        "https://github.com/pallets/werkzeug",
        "https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028",
        "https://github.com/pallets/werkzeug/releases/tag/2.2.3",
        "https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q",
        "https://github.com/pypa/advisory-database/tree/main/vulns/werkzeug/PYSEC-2023-57.yaml",
        "https://linux.oracle.com/cve/CVE-2023-23934.html",
        "https://linux.oracle.com/errata/ELSA-2023-12709.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-23934",
        "https://security.netapp.com/advisory/ntap-20230818-0003",
        "https://security.netapp.com/advisory/ntap-20230818-0003/",
        "https://ubuntu.com/security/notices/USN-5948-1",
        "https://ubuntu.com/security/notices/USN-5948-2",
        "https://www.cve.org/CVERecord?id=CVE-2023-23934",
        "https://www.debian.org/security/2023/dsa-5470"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2023-23934",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2023-5752",
      "package_name": "pip",
      "installed_version": "23.0.1",
      "severity": "MEDIUM",
      "title": "pip: Mercurial configuration injectable in repo revision when installing via pip",
      "description": "When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.",
      "fixed_version": "23.3",
      "cvss": {
        "bitnami": {
          "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
          "V3Score": 3.3
        },
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
          "V3Score": 5.5
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
          "V3Score": 3.3
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
          "V3Score": 3.3
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2023-5752",
        "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2023-228.yaml",
        "https://github.com/pypa/pip",
        "https://github.com/pypa/pip/commit/389cb799d0da9a840749fcd14878928467ed49b4",
        "https://github.com/pypa/pip/pull/12306",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/",
        "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL",
        "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-5752",
        "https://www.cve.org/CVERecord?id=CVE-2023-5752"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2023-5752",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2025-8869",
      "package_name": "pip",
      "installed_version": "23.0.1",
      "severity": "MEDIUM",
      "title": "pip: pip missing checks on symbolic link extraction",
      "description": "When extracting a tar archive pip may not check symbolic links point into the extraction directory if the tarfile module doesn't implement PEP 706.\nNote that upgrading pip to a \"fixed\" version for this vulnerability doesn't fix all known vulnerabilities that are remediated by using a Python version that implements PEP 706.\n\nNote that this is a vulnerability in pip's fallback implementation of tar extraction for Python versions that don't implement PEP 706\nand therefore are not secure to all vulnerabilities in the Python 'tarfile' module. If you're using a Python version that implements PEP 706\nthen pip doesn't use the \"vulnerable\" fallback code.\n\nMitigations include upgrading to a version of pip that includes the fix, upgrading to a Python version that implements PEP 706 (Python >=3.9.17, >=3.10.12, >=3.11.4, or >=3.12),\napplying the linked patch, or inspecting source distributions (sdists) before installation as is already a best-practice.",
      "fixed_version": "",
      "cvss": {
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:H/A:N",
          "V3Score": 5.3
        }
      },
      "references": [
        "https://access.redhat.com/security/cve/CVE-2025-8869",
        "https://github.com/pypa/pip",
        "https://github.com/pypa/pip/commit/f2b92314da012b9fffa36b3f3e67748a37ef464a",
        "https://github.com/pypa/pip/pull/13550",
        "https://mail.python.org/archives/list/security-announce@python.org/thread/IF5A3GCJY3VH7BVHJKOWOJFKTW7VFQEN",
        "https://mail.python.org/archives/list/security-announce@python.org/thread/IF5A3GCJY3VH7BVHJKOWOJFKTW7VFQEN/",
        "https://nvd.nist.gov/vuln/detail/CVE-2025-8869",
        "https://pip.pypa.io/en/stable/news/#v25-2",
        "https://www.cve.org/CVERecord?id=CVE-2025-8869"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2025-8869",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2022-40897",
      "package_name": "setuptools",
      "installed_version": "58.1.0",
      "severity": "HIGH",
      "title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
      "description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
      "fixed_version": "65.5.1",
      "cvss": {
        "bitnami": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 5.9
        },
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 7.5
        },
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 5.9
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "V3Score": 5.9
        }
      },
      "references": [
        "https://access.redhat.com/errata/RHSA-2023:0952",
        "https://access.redhat.com/security/cve/CVE-2022-40897",
        "https://bugzilla.redhat.com/2158559",
        "https://bugzilla.redhat.com/show_bug.cgi?id=2158559",
        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897",
        "https://errata.almalinux.org/9/ALSA-2023-0952.html",
        "https://errata.rockylinux.org/RLSA-2023:0952",
        "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2022-43012.yaml",
        "https://github.com/pypa/setuptools",
        "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
        "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
        "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
        "https://github.com/pypa/setuptools/issues/3659",
        "https://linux.oracle.com/cve/CVE-2022-40897.html",
        "https://linux.oracle.com/errata/ELSA-2024-2987.html",
        "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
        "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
        "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
        "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
        "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
        "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
        "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
        "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
        "https://pyup.io/vulnerabilities/CVE-2022-40897/52495",
        "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
        "https://security.netapp.com/advisory/ntap-20230214-0001",
        "https://security.netapp.com/advisory/ntap-20230214-0001/",
        "https://security.netapp.com/advisory/ntap-20240621-0006",
        "https://security.netapp.com/advisory/ntap-20240621-0006/",
        "https://setuptools.pypa.io/en/latest",
        "https://ubuntu.com/security/notices/USN-5817-1",
        "https://www.cve.org/CVERecord?id=CVE-2022-40897"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2022-40897",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2024-6345",
      "package_name": "setuptools",
      "installed_version": "58.1.0",
      "severity": "HIGH",
      "title": "pypa/setuptools: Remote code execution via download functions in the package_index module in pypa/setuptools",
      "description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
      "fixed_version": "70.0.0",
      "cvss": {
        "bitnami": {
          "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "V3Score": 8.8
        },
        "ghsa": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "V3Score": 8.8
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "V3Score": 8.8
        }
      },
      "references": [
        "https://access.redhat.com/errata/RHSA-2024:6726",
        "https://access.redhat.com/security/cve/CVE-2024-6345",
        "https://bugzilla.redhat.com/2297771",
        "https://bugzilla.redhat.com/show_bug.cgi?id=2297771",
        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-6345",
        "https://errata.almalinux.org/9/ALSA-2024-6726.html",
        "https://errata.rockylinux.org/RLSA-2024:6726",
        "https://github.com/pypa/setuptools",
        "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0",
        "https://github.com/pypa/setuptools/pull/4332",
        "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5",
        "https://linux.oracle.com/cve/CVE-2024-6345.html",
        "https://linux.oracle.com/errata/ELSA-2024-6726.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
        "https://ubuntu.com/security/notices/USN-7002-1",
        "https://www.cve.org/CVERecord?id=CVE-2024-6345"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2024-6345",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    },
    {
      "id": "CVE-2025-47273",
      "package_name": "setuptools",
      "installed_version": "58.1.0",
      "severity": "HIGH",
      "title": "setuptools: Path Traversal Vulnerability in setuptools PackageIndex",
      "description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.",
      "fixed_version": "78.1.1",
      "cvss": {
        "nvd": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
          "V3Score": 8.8
        },
        "redhat": {
          "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
          "V3Score": 7.1
        }
      },
      "references": [
        "https://access.redhat.com/errata/RHSA-2025:13578",
        "https://access.redhat.com/security/cve/CVE-2025-47273",
        "https://bugzilla.redhat.com/2366982",
        "https://bugzilla.redhat.com/show_bug.cgi?id=2366982",
        "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-47273",
        "https://errata.almalinux.org/9/ALSA-2025-13578.html",
        "https://errata.rockylinux.org/RLSA-2025:11036",
        "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2025-49.yaml",
        "https://github.com/pypa/setuptools",
        "https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88",
        "https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b",
        "https://github.com/pypa/setuptools/issues/4946",
        "https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf",
        "https://linux.oracle.com/cve/CVE-2025-47273.html",
        "https://linux.oracle.com/errata/ELSA-2025-9940.html",
        "https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2025-47273",
        "https://ubuntu.com/security/notices/USN-7544-1",
        "https://www.cve.org/CVERecord?id=CVE-2025-47273"
      ],
      "primary_url": "https://avd.aquasec.com/nvd/cve-2025-47273",
      "data_source": {
        "ID": "ghsa",
        "Name": "GitHub Security Advisory pip",
        "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "package_type": "python-pkg"
    }
  ]
}